apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
        - name: node-todo-app
          image: sunitabachhav2007/node-todo-test:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: node-todo-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: node-todo-app